# Generated by Django 5.0.7 on 2024-07-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="img")),
                ("desc", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
